version: '3.8'

services:
  base:
    image: taehun3446/setup:opencv
    container_name: base
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    stdin_open: true
    tty: true
